services:
  redis:
    image: redis:alpine
    command: redis-server
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cloud-storage
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}