services:
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  cloud-storage:
    image: zloymumu/cloud-storage:0.0.1-SNAPSHOT
    container_name: cloud-storage
    environment:
      SPRING_PROFILES_ACTIVE: prod
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_HOST: minio
    restart: always
    ports:
      - "8080:8080"

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

  frontend:
    build: /frontend
    container_name: cloud-storage-frontend
    ports:
      - "80:80"
    environment:
      BACKEND_URL: http://cloud-storage:8080