spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
      example:
        cloudstorage: DEBUG