spring:
  application:
    name: cloud-storage
  datasource:
    username:
      ${POSTGRES_USER}
    password:
      ${POSTGRES_PASSWORD}
  data:
    redis:
      password: ${REDIS_PASSWORD}
  jpa:
    open-in-view: false

