spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  minio:
    url: http://${MINIO_HOST:localhost}:9000
    access_key: ${MINIO_ROOT_USER}
    secret_key: ${MINIO_ROOT_PASSWORD}
    bucket_name: user-files
  application:
    name: cloud-storage
  datasource:
    url:
      jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB}
    username:
      ${POSTGRES_USER}
    password:
      ${POSTGRES_PASSWORD}
  data:
    redis:
      password: ${REDIS_PASSWORD}
      host: ${REDIS_HOST:localhost}
  jpa:
    open-in-view: false
