spring:
  application:
    name: cloud-storage
  datasource:
    url:
      jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB}
    username:
      ${POSTGRES_USER}
    password:
      ${POSTGRES_PASSWORD}
  data:
    redis:
      password: ${REDIS_PASSWORD}
      host: ${REDIS_HOST:localhost}
  jpa:
    open-in-view: false
