apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-storage-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-storage-minio
  template:
    metadata:
      labels:
        app: cloud-storage-minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          command: [ "/usr/bin/minio", "server", "/data", "--console-address", ":9001" ]
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: cloud-storage-secrets
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloud-storage-secrets
                  key: MINIO_ROOT_PASSWORD
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: cloud-storage-minio-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-storage-minio
spec:
  selector:
    app: cloud-storage-minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-storage-minio-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi