apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-storage-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-storage-redis
  template:
    metadata:
      labels:
        app: cloud-storage-redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          command: [ "redis-server", "--requirepass $(REDIS_PASSWORD)" ]
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloud-storage-secrets
                  key: REDIS_PASSWORD
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-storage-redis
spec:
  selector:
    app: cloud-storage-redis
  ports:
    - port: 6379