apiVersion: v1
kind: Secret
metadata:
  name: cloud-storage-secrets
type: Opaque
stringData:
  POSTGRES_DB: "CHANGE_ME_DB_NAME"
  POSTGRES_USER: "CHANGE_ME_DB_USER"
  POSTGRES_PASSWORD: "CHANGE_ME_DB_PASSWORD"
  REDIS_PASSWORD: "CHANGE_ME_REDIS_PASSWORD"