apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-storage-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-storage-postgres
  template:
    metadata:
      labels:
        app: cloud-storage-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          envFrom:
            - secretRef:
                name: cloud-storage-secrets
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: cloud-storage-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-storage-postgres
spec:
  selector:
    app: cloud-storage-postgres
  ports:
    - port: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-storage-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi