CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS username_index ON users (username);
